[package]
edition = "2021"
readme = "README.md"
name = "embassy-st7789v-driver"
version = "1.2.0"
description = "ST7789 TFT LCD embassy async driver with embedded-graphics support"
license = "MIT"
repository = "https://github.com/wendell1002/ST7789v-driver"
keywords = ["embassy-async-hal-driver", "st7789", "display", "on_std", "async"]
documentation = "https://docs.rs/st7789v-driver"

[dependencies]
embedded-hal-async = { version = "1.0" }
embassy-futures = { version = "0.1.0" }
embedded-graphics-core = "0.4.0"
embedded-hal = "1.0.0"
heapless = "0.9.1"
[lib]
path = "src/lib.rs"
name = "embassy_st7789v_driver"
test = false
bench = false

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true # <-
incremental = false
opt-level = 'z'         # <-
overflow-checks = true  # <-

[profile.release]
codegen-units = 1 # better optimizations
debug = true      # symbols are nice and they don't increase the size on Flash
lto = true        # better optimizations
